version: "3.9"
name: 'backendstresstest'

services:
  api1: # API - Instance 1
    image: wbail/backendstresstest-2023-q3
    build:
      context: src
      dockerfile: BackendStressTest.Api/Dockerfile
    hostname: api1
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__BackendStressTestDb=Host=db;Port=5432;Username=admin;Password=postgrespw;Database=backendstresstestdb;Pooling=true;Minimum Pool Size=300;Maximum Pool Size=450;Multiplexing=true;Timeout=5;Command Timeout=5;Cancellation Timeout=-1;No Reset On Close=true;
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.7GB"
    networks:
      - backendstresstest-network
    healthcheck:
      test: curl -o /dev/null -fs --retry 0 --head http://localhost:9999/healthz || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 2s

  api2: # API - Instance 2
    image: wbail/backendstresstest-2023-q3
    build:
      context: src
      dockerfile: BackendStressTest.Api/Dockerfile
    hostname: api2
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__BackendStressTestDb=Host=db;Port=5432;Username=admin;Password=postgrespw;Database=backendstresstestdb;Pooling=true;Minimum Pool Size=300;Maximum Pool Size=450;Multiplexing=true;Timeout=5;Command Timeout=5;Cancellation Timeout=-1;No Reset On Close=true;
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.7GB"
    networks:
      - backendstresstest-network
    healthcheck:
      test: curl -o /dev/null -fs --retry 0 --head http://localhost:9999/healthz || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 2s

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.25GB"
    networks:
      - backendstresstest-network

  db: # Database
    image: postgres:latest
    command: 'postgres -c max_connections=1000 -c shared_buffers=512MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=backendstresstestdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.35GB"
    networks:
      - backendstresstest-network
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "admin", "--password", "postgrespw"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  backendstresstest-network:
    driver: bridge